name: blindfold-go

channels:
- conda-forge
- pytorch
- defaults

dependencies:
- speechrecognition=3.10.1
- comtypes=1.3.1
- pyaudio=0.2.11
- python=3.8.19
- pip=23.3.1
- cmake
- pip :
  - sente==0.4.0
  - pyttsx3==2.90
  - flask==3.0.3
#- pip :
#  - python-espeak==0.6.3





